PRINT('Delete existing tables')





IF EXISTS (
SELECT * FROM SYS.objects WHERE NAME = 'VEHICLESREMOVED' AND TYPE_DESC = 'USER_TABLE')

BEGIN
	DROP TABLE VEHICLESREMOVED
	PRINT('TABLE VEHCILESREMOVED FOUND EXISTING AND SO DROPPED')
END
ELSE
BEGIN
	
	PRINT('Table VEHCILESREMOVED NOT found and nothing to delete.')
END


IF EXISTS (
SELECT * FROM SYS.objects WHERE NAME = 'BOOKING_VEHICLESREMOVED' AND TYPE_DESC = 'USER_TABLE')

BEGIN
	DROP TABLE BOOKING_VEHICLESREMOVED
	PRINT('TABLE BOOKING_VEHICLESREMOVED FOUND EXISTING AND SO DROPPED')
END 
ELSE
BEGIN
	PRINT('Table BOOKING_VEHICLESREMOVED ')
END

