IF EXISTS (
SELECT * FROM SYS.objects WHERE NAME = 'VEHICLESREMOVED' AND TYPE_DESC = 'USER_TABLE')

BEGIN
	DROP TABLE VEHICLESREMOVED
	PRINT('TABLE VEHICLESREMOVED FOUND EXISTING AND SO DROPPED')
END
ELSE
BEGIN
	PRINT('Table VEHICLESREMOVED does not exist.')
END


GO
CREATE TABLE VEHICLESREMOVED
(VehicleID int)