

CREATE VIEW [dbo].[vLink_HRCOM_ADDRESS_REF]
AS
SELECT     ADDRESS_CODE, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_CITY, ADDRESS_STATE, COUNTRY_CODE, POST_CODE, 
                      TELEPHONE_1, TELEPHONE_2, TELEPHONE_3, FACSIMILE_1, FACSIMILE_2, EMAIL_ADDRESS, ROW_STATUS, CLOSED_USER, CLOSED_DATE, 
                      CLOSED_TIME, CLOSED_TERM, CLOSED_WINDOW, CRUSER, CRDATEI, CRTIMEI, CRTERM, CRWINDOW, LAST_MOD_USER, LAST_MOD_DATEI, 
                      LAST_MOD_TIMEI, LAST_MOD_TERM, LAST_MOD_WINDOW, VERS, MOBILE_PHONE, DPID_NBR, MOBILE_PHONE_2, EMAIL_ADDRESS_2
FROM        [FinProd].[dbo].HRCOM_ADDRESS_REF


