CREATE PROCEDURE [spVehicle_insert]
	(@VehicleID_1 	[int],
	 @ParkingSpace_2 	[varchar](15),
	 @Registration_3 	[varchar](15),
	 @vehicle_model_id_4 	[int],
	 @vehicle_type_id_5 	[int],
	 @SeatingCapacity_6 	[int],
	 @BookingCount_7 	[int],
	 @Weighting_8 	[int],
	 @Colour_9 	[varchar](20),
	 @Information_10 	[varchar](255),
	 @AcquisitionDate_11 	[datetime],
	 @DisposalDate_12 	[datetime],
	 @AssignedToPersonId_13 	[int],
	 @DivisionId_14 	[smallint],
	 @key_location_id_15 	[smallint],
	 @Avail_Now_16 	[bit],
	 @Avail_Early_17 	[bit],
	 @Avail_Late_18 	[bit],
	 @Avail_Overnight_19 	[bit],
	 @Reserve_Unit_20 	[bit],
	 @Reserve_Special_Usage_21 	[bit],
	 @OrgUnitID_22 	[int],
	 @Special_Usage_Description_23 	[nvarchar](150))

AS INSERT INTO [dbo].[tblVehicle] 
	 ( [VehicleID],
	 [ParkingSpace],
	 [Registration],
	 [vehicle_model_id],
	 [vehicle_type_id],
	 [SeatingCapacity],
	 [BookingCount],
	 [Weighting],
	 [Colour],
	 [Information],
	 [AcquisitionDate],
	 [DisposalDate],
	 [AssignedToPersonId],
	 [DivisionId],
	 [key_location_id],
	 [Avail_Now],
	 [Avail_Early],
	 [Avail_Late],
	 [Avail_Overnight],
	 [Reserve_Unit],
	 [Reserve_Special_Usage],
	 [OrgUnitID],
	 [Special_Usage_Description]) 
 
VALUES 
	( @VehicleID_1,
	 @ParkingSpace_2,
	 @Registration_3,
	 @vehicle_model_id_4,
	 @vehicle_type_id_5,
	 @SeatingCapacity_6,
	 @BookingCount_7,
	 @Weighting_8,
	 @Colour_9,
	 @Information_10,
	 @AcquisitionDate_11,
	 @DisposalDate_12,
	 @AssignedToPersonId_13,
	 @DivisionId_14,
	 @key_location_id_15,
	 @Avail_Now_16,
	 @Avail_Early_17,
	 @Avail_Late_18,
	 @Avail_Overnight_19,
	 @Reserve_Unit_20,
	 @Reserve_Special_Usage_21,
	 @OrgUnitID_22,
	 @Special_Usage_Description_23)